name: Profile Activity Generator

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Update every hour

jobs:
  generate-profile-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate Profile Activity
        uses: omidnikrah/profile-activity-generator@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
